# Copy yanked files to the system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", 'plugin clipboard -- --action=copy' ]
desc = "Yank selected files (copy)"

# Cut selected files to the system clipboard
[[mgr.prepend_keymap]]
on  = "x"
run = [ "yank --cut", 'plugin clipboard -- --action=copy' ]
desc = "Yank selected files (cut)"

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on  = "<C-p>"
run = [ 'plugin clipboard -- --action=paste' ]

# Edit current file with neovim
[[mgr.prepend_keymap]]
on   = "e"
run  = "shell --block nvim %h"
desc = "Edit with neovim"

# Go to Windows drives using fzf
[[mgr.prepend_keymap]]
on   = [ "g", ":" ]
run  = "plugin goto-drives"
desc = "Go to drives"

