add_newline = false

format="$username@$os$all$linebreak$character"

[os]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❌](bold red)"
vicmd_symbol = "[❯](bold blue)"

[fill]
symbol = " "

[git_status]
format = "$all_status$ahead_behind"

up_to_date = "[✓](bold green) "
conflicted = "⚔️ "
ahead      = "↑${count} "
diverged   = "↑${ahead_count}↓${behind_count} "
behind     = "↓${count} "
stashed    = "[⚑$count](bold blue) "
staged     = "[✚$count](green) "
modified   = "📝${count} "
renamed    = "[»$count](green) "
deleted    = "🗑️${count} "
untracked  = "[?$count](cyan) "
style      = "bright-white"

[git_commit]
tag_disabled = false
commit_hash_length = 7
tag_symbol = "🔖 "

[hostname]
disabled = true

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[$user]($style)'
